// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/playmessages.proto

package playmessages;

public final class Playmessages {
  private Playmessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class PlayRequestWrapper extends
      com.google.protobuf.GeneratedMessage {
    // Use PlayRequestWrapper.newBuilder() to construct.
    private PlayRequestWrapper() {
      initFields();
    }
    private PlayRequestWrapper(boolean noInit) {}
    
    private static final PlayRequestWrapper defaultInstance;
    public static PlayRequestWrapper getDefaultInstance() {
      return defaultInstance;
    }
    
    public PlayRequestWrapper getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return playmessages.Playmessages.internal_static_playmessages_PlayRequestWrapper_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return playmessages.Playmessages.internal_static_playmessages_PlayRequestWrapper_fieldAccessorTable;
    }
    
    // optional .playmessages.IncomingMessage incomingMessage = 1;
    public static final int INCOMINGMESSAGE_FIELD_NUMBER = 1;
    private boolean hasIncomingMessage;
    private playmessages.Playmessages.IncomingMessage incomingMessage_;
    public boolean hasIncomingMessage() { return hasIncomingMessage; }
    public playmessages.Playmessages.IncomingMessage getIncomingMessage() { return incomingMessage_; }
    
    private void initFields() {
      incomingMessage_ = playmessages.Playmessages.IncomingMessage.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (hasIncomingMessage()) {
        if (!getIncomingMessage().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasIncomingMessage()) {
        output.writeMessage(1, getIncomingMessage());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasIncomingMessage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getIncomingMessage());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static playmessages.Playmessages.PlayRequestWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static playmessages.Playmessages.PlayRequestWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static playmessages.Playmessages.PlayRequestWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static playmessages.Playmessages.PlayRequestWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static playmessages.Playmessages.PlayRequestWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static playmessages.Playmessages.PlayRequestWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static playmessages.Playmessages.PlayRequestWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static playmessages.Playmessages.PlayRequestWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static playmessages.Playmessages.PlayRequestWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static playmessages.Playmessages.PlayRequestWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(playmessages.Playmessages.PlayRequestWrapper prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private playmessages.Playmessages.PlayRequestWrapper result;
      
      // Construct using playmessages.Playmessages.PlayRequestWrapper.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new playmessages.Playmessages.PlayRequestWrapper();
        return builder;
      }
      
      protected playmessages.Playmessages.PlayRequestWrapper internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new playmessages.Playmessages.PlayRequestWrapper();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return playmessages.Playmessages.PlayRequestWrapper.getDescriptor();
      }
      
      public playmessages.Playmessages.PlayRequestWrapper getDefaultInstanceForType() {
        return playmessages.Playmessages.PlayRequestWrapper.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public playmessages.Playmessages.PlayRequestWrapper build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private playmessages.Playmessages.PlayRequestWrapper buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public playmessages.Playmessages.PlayRequestWrapper buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        playmessages.Playmessages.PlayRequestWrapper returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof playmessages.Playmessages.PlayRequestWrapper) {
          return mergeFrom((playmessages.Playmessages.PlayRequestWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(playmessages.Playmessages.PlayRequestWrapper other) {
        if (other == playmessages.Playmessages.PlayRequestWrapper.getDefaultInstance()) return this;
        if (other.hasIncomingMessage()) {
          mergeIncomingMessage(other.getIncomingMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              playmessages.Playmessages.IncomingMessage.Builder subBuilder = playmessages.Playmessages.IncomingMessage.newBuilder();
              if (hasIncomingMessage()) {
                subBuilder.mergeFrom(getIncomingMessage());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setIncomingMessage(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .playmessages.IncomingMessage incomingMessage = 1;
      public boolean hasIncomingMessage() {
        return result.hasIncomingMessage();
      }
      public playmessages.Playmessages.IncomingMessage getIncomingMessage() {
        return result.getIncomingMessage();
      }
      public Builder setIncomingMessage(playmessages.Playmessages.IncomingMessage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasIncomingMessage = true;
        result.incomingMessage_ = value;
        return this;
      }
      public Builder setIncomingMessage(playmessages.Playmessages.IncomingMessage.Builder builderForValue) {
        result.hasIncomingMessage = true;
        result.incomingMessage_ = builderForValue.build();
        return this;
      }
      public Builder mergeIncomingMessage(playmessages.Playmessages.IncomingMessage value) {
        if (result.hasIncomingMessage() &&
            result.incomingMessage_ != playmessages.Playmessages.IncomingMessage.getDefaultInstance()) {
          result.incomingMessage_ =
            playmessages.Playmessages.IncomingMessage.newBuilder(result.incomingMessage_).mergeFrom(value).buildPartial();
        } else {
          result.incomingMessage_ = value;
        }
        result.hasIncomingMessage = true;
        return this;
      }
      public Builder clearIncomingMessage() {
        result.hasIncomingMessage = false;
        result.incomingMessage_ = playmessages.Playmessages.IncomingMessage.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:playmessages.PlayRequestWrapper)
    }
    
    static {
      defaultInstance = new PlayRequestWrapper(true);
      playmessages.Playmessages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:playmessages.PlayRequestWrapper)
  }
  
  public static final class IncomingMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use IncomingMessage.newBuilder() to construct.
    private IncomingMessage() {
      initFields();
    }
    private IncomingMessage(boolean noInit) {}
    
    private static final IncomingMessage defaultInstance;
    public static IncomingMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public IncomingMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return playmessages.Playmessages.internal_static_playmessages_IncomingMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return playmessages.Playmessages.internal_static_playmessages_IncomingMessage_fieldAccessorTable;
    }
    
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasName) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasName()) {
        output.writeString(1, getName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static playmessages.Playmessages.IncomingMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static playmessages.Playmessages.IncomingMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static playmessages.Playmessages.IncomingMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static playmessages.Playmessages.IncomingMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static playmessages.Playmessages.IncomingMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static playmessages.Playmessages.IncomingMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static playmessages.Playmessages.IncomingMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static playmessages.Playmessages.IncomingMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static playmessages.Playmessages.IncomingMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static playmessages.Playmessages.IncomingMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(playmessages.Playmessages.IncomingMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private playmessages.Playmessages.IncomingMessage result;
      
      // Construct using playmessages.Playmessages.IncomingMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new playmessages.Playmessages.IncomingMessage();
        return builder;
      }
      
      protected playmessages.Playmessages.IncomingMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new playmessages.Playmessages.IncomingMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return playmessages.Playmessages.IncomingMessage.getDescriptor();
      }
      
      public playmessages.Playmessages.IncomingMessage getDefaultInstanceForType() {
        return playmessages.Playmessages.IncomingMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public playmessages.Playmessages.IncomingMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private playmessages.Playmessages.IncomingMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public playmessages.Playmessages.IncomingMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        playmessages.Playmessages.IncomingMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof playmessages.Playmessages.IncomingMessage) {
          return mergeFrom((playmessages.Playmessages.IncomingMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(playmessages.Playmessages.IncomingMessage other) {
        if (other == playmessages.Playmessages.IncomingMessage.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string name = 1;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:playmessages.IncomingMessage)
    }
    
    static {
      defaultInstance = new IncomingMessage(true);
      playmessages.Playmessages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:playmessages.IncomingMessage)
  }
  
  public static final class PlayResponseWrapper extends
      com.google.protobuf.GeneratedMessage {
    // Use PlayResponseWrapper.newBuilder() to construct.
    private PlayResponseWrapper() {
      initFields();
    }
    private PlayResponseWrapper(boolean noInit) {}
    
    private static final PlayResponseWrapper defaultInstance;
    public static PlayResponseWrapper getDefaultInstance() {
      return defaultInstance;
    }
    
    public PlayResponseWrapper getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return playmessages.Playmessages.internal_static_playmessages_PlayResponseWrapper_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return playmessages.Playmessages.internal_static_playmessages_PlayResponseWrapper_fieldAccessorTable;
    }
    
    // optional .playmessages.OutgoingMessage outgoingMessage = 1;
    public static final int OUTGOINGMESSAGE_FIELD_NUMBER = 1;
    private boolean hasOutgoingMessage;
    private playmessages.Playmessages.OutgoingMessage outgoingMessage_;
    public boolean hasOutgoingMessage() { return hasOutgoingMessage; }
    public playmessages.Playmessages.OutgoingMessage getOutgoingMessage() { return outgoingMessage_; }
    
    private void initFields() {
      outgoingMessage_ = playmessages.Playmessages.OutgoingMessage.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (hasOutgoingMessage()) {
        if (!getOutgoingMessage().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasOutgoingMessage()) {
        output.writeMessage(1, getOutgoingMessage());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasOutgoingMessage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getOutgoingMessage());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static playmessages.Playmessages.PlayResponseWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static playmessages.Playmessages.PlayResponseWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static playmessages.Playmessages.PlayResponseWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static playmessages.Playmessages.PlayResponseWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static playmessages.Playmessages.PlayResponseWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static playmessages.Playmessages.PlayResponseWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static playmessages.Playmessages.PlayResponseWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static playmessages.Playmessages.PlayResponseWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static playmessages.Playmessages.PlayResponseWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static playmessages.Playmessages.PlayResponseWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(playmessages.Playmessages.PlayResponseWrapper prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private playmessages.Playmessages.PlayResponseWrapper result;
      
      // Construct using playmessages.Playmessages.PlayResponseWrapper.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new playmessages.Playmessages.PlayResponseWrapper();
        return builder;
      }
      
      protected playmessages.Playmessages.PlayResponseWrapper internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new playmessages.Playmessages.PlayResponseWrapper();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return playmessages.Playmessages.PlayResponseWrapper.getDescriptor();
      }
      
      public playmessages.Playmessages.PlayResponseWrapper getDefaultInstanceForType() {
        return playmessages.Playmessages.PlayResponseWrapper.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public playmessages.Playmessages.PlayResponseWrapper build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private playmessages.Playmessages.PlayResponseWrapper buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public playmessages.Playmessages.PlayResponseWrapper buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        playmessages.Playmessages.PlayResponseWrapper returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof playmessages.Playmessages.PlayResponseWrapper) {
          return mergeFrom((playmessages.Playmessages.PlayResponseWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(playmessages.Playmessages.PlayResponseWrapper other) {
        if (other == playmessages.Playmessages.PlayResponseWrapper.getDefaultInstance()) return this;
        if (other.hasOutgoingMessage()) {
          mergeOutgoingMessage(other.getOutgoingMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              playmessages.Playmessages.OutgoingMessage.Builder subBuilder = playmessages.Playmessages.OutgoingMessage.newBuilder();
              if (hasOutgoingMessage()) {
                subBuilder.mergeFrom(getOutgoingMessage());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setOutgoingMessage(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .playmessages.OutgoingMessage outgoingMessage = 1;
      public boolean hasOutgoingMessage() {
        return result.hasOutgoingMessage();
      }
      public playmessages.Playmessages.OutgoingMessage getOutgoingMessage() {
        return result.getOutgoingMessage();
      }
      public Builder setOutgoingMessage(playmessages.Playmessages.OutgoingMessage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasOutgoingMessage = true;
        result.outgoingMessage_ = value;
        return this;
      }
      public Builder setOutgoingMessage(playmessages.Playmessages.OutgoingMessage.Builder builderForValue) {
        result.hasOutgoingMessage = true;
        result.outgoingMessage_ = builderForValue.build();
        return this;
      }
      public Builder mergeOutgoingMessage(playmessages.Playmessages.OutgoingMessage value) {
        if (result.hasOutgoingMessage() &&
            result.outgoingMessage_ != playmessages.Playmessages.OutgoingMessage.getDefaultInstance()) {
          result.outgoingMessage_ =
            playmessages.Playmessages.OutgoingMessage.newBuilder(result.outgoingMessage_).mergeFrom(value).buildPartial();
        } else {
          result.outgoingMessage_ = value;
        }
        result.hasOutgoingMessage = true;
        return this;
      }
      public Builder clearOutgoingMessage() {
        result.hasOutgoingMessage = false;
        result.outgoingMessage_ = playmessages.Playmessages.OutgoingMessage.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:playmessages.PlayResponseWrapper)
    }
    
    static {
      defaultInstance = new PlayResponseWrapper(true);
      playmessages.Playmessages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:playmessages.PlayResponseWrapper)
  }
  
  public static final class OutgoingMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use OutgoingMessage.newBuilder() to construct.
    private OutgoingMessage() {
      initFields();
    }
    private OutgoingMessage(boolean noInit) {}
    
    private static final OutgoingMessage defaultInstance;
    public static OutgoingMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public OutgoingMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return playmessages.Playmessages.internal_static_playmessages_OutgoingMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return playmessages.Playmessages.internal_static_playmessages_OutgoingMessage_fieldAccessorTable;
    }
    
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasName) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasName()) {
        output.writeString(1, getName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static playmessages.Playmessages.OutgoingMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static playmessages.Playmessages.OutgoingMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static playmessages.Playmessages.OutgoingMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static playmessages.Playmessages.OutgoingMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static playmessages.Playmessages.OutgoingMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static playmessages.Playmessages.OutgoingMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static playmessages.Playmessages.OutgoingMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static playmessages.Playmessages.OutgoingMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static playmessages.Playmessages.OutgoingMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static playmessages.Playmessages.OutgoingMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(playmessages.Playmessages.OutgoingMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private playmessages.Playmessages.OutgoingMessage result;
      
      // Construct using playmessages.Playmessages.OutgoingMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new playmessages.Playmessages.OutgoingMessage();
        return builder;
      }
      
      protected playmessages.Playmessages.OutgoingMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new playmessages.Playmessages.OutgoingMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return playmessages.Playmessages.OutgoingMessage.getDescriptor();
      }
      
      public playmessages.Playmessages.OutgoingMessage getDefaultInstanceForType() {
        return playmessages.Playmessages.OutgoingMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public playmessages.Playmessages.OutgoingMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private playmessages.Playmessages.OutgoingMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public playmessages.Playmessages.OutgoingMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        playmessages.Playmessages.OutgoingMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof playmessages.Playmessages.OutgoingMessage) {
          return mergeFrom((playmessages.Playmessages.OutgoingMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(playmessages.Playmessages.OutgoingMessage other) {
        if (other == playmessages.Playmessages.OutgoingMessage.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string name = 1;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:playmessages.OutgoingMessage)
    }
    
    static {
      defaultInstance = new OutgoingMessage(true);
      playmessages.Playmessages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:playmessages.OutgoingMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_playmessages_PlayRequestWrapper_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_playmessages_PlayRequestWrapper_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_playmessages_IncomingMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_playmessages_IncomingMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_playmessages_PlayResponseWrapper_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_playmessages_PlayResponseWrapper_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_playmessages_OutgoingMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_playmessages_OutgoingMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026src/playmessages.proto\022\014playmessages\"L" +
      "\n\022PlayRequestWrapper\0226\n\017incomingMessage\030" +
      "\001 \001(\0132\035.playmessages.IncomingMessage\"\037\n\017" +
      "IncomingMessage\022\014\n\004name\030\001 \002(\t\"M\n\023PlayRes" +
      "ponseWrapper\0226\n\017outgoingMessage\030\001 \001(\0132\035." +
      "playmessages.OutgoingMessage\"\037\n\017Outgoing" +
      "Message\022\014\n\004name\030\001 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_playmessages_PlayRequestWrapper_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_playmessages_PlayRequestWrapper_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_playmessages_PlayRequestWrapper_descriptor,
              new java.lang.String[] { "IncomingMessage", },
              playmessages.Playmessages.PlayRequestWrapper.class,
              playmessages.Playmessages.PlayRequestWrapper.Builder.class);
          internal_static_playmessages_IncomingMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_playmessages_IncomingMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_playmessages_IncomingMessage_descriptor,
              new java.lang.String[] { "Name", },
              playmessages.Playmessages.IncomingMessage.class,
              playmessages.Playmessages.IncomingMessage.Builder.class);
          internal_static_playmessages_PlayResponseWrapper_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_playmessages_PlayResponseWrapper_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_playmessages_PlayResponseWrapper_descriptor,
              new java.lang.String[] { "OutgoingMessage", },
              playmessages.Playmessages.PlayResponseWrapper.class,
              playmessages.Playmessages.PlayResponseWrapper.Builder.class);
          internal_static_playmessages_OutgoingMessage_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_playmessages_OutgoingMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_playmessages_OutgoingMessage_descriptor,
              new java.lang.String[] { "Name", },
              playmessages.Playmessages.OutgoingMessage.class,
              playmessages.Playmessages.OutgoingMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
